### ISSUE TITLE
[Crash] I Got This Issue. How to fix It?

### ISSUE THREAD

**Issue by lixorhaxz** [DrOreo002/GrowtopiaBot#2]
While Debuging
![Screenshot_2020-01-19-07-56-58-549_com microsoft rdc android](https://user-images.githubusercontent.com/47329758/72672182-77a21000-3a91-11ea-9c83-af717d07f295.png)
While Running
![Screenshot_2020-01-19-07-55-26-317_com microsoft rdc android](https://user-images.githubusercontent.com/47329758/72672183-783aa680-3a91-11ea-8233-f60f55a08d0d.png)

**Comment by WoofHax** [comment]
Create new file called bot.json then 
{
  "username": "HelloWorld",
  "password": "LMAO",
  "gameVersion": "2.999",
  "targetWorld": "DROREOITEM",
  "publicOwnership": "true"
}
Copy paste on Bot.json

**Comment by arshizx** [comment]
it must be

```json
{
"username": "HelloWorld",
"password": "LMAO",
"gameVersion": "2.999",
"targetWorld": "DROREOITEM",
"publicOwnership": true
}
```

**Comment by lixorhaxz** [comment]
> Create new file called bot.json then
> {
> "username": "HelloWorld",
> "password": "LMAO",
> "gameVersion": "2.999",
> "targetWorld": "DROREOITEM",
> "publicOwnership": "true"
> }
> Copy paste on Bot.json

still same

**Comment by DrOreo002** [comment]
Hmmm, will take a look at this now

**Comment by DrOreo002** [comment]
Should be fixed now, thanks to @arshizx sorry for not replying. I got other works to do
