### ISSUE TITLE
not working.

### ISSUE THREAD

**Issue by NIGHT-l33t** [DrOreo002/GrowtopiaBot#4]
not working.

**Comment by atomiclucky** [comment]
yeah, same. it just doesn't connect! i tried changing the login packet (the protocol, etc), but no positive results

**Comment by NIGHT-l33t** [comment]
> yeah, same. it just doesn't connect! i tried changing the login packet (the protocol, etc), but no positive results

You have discord?

**Comment by DrOreo002** [comment]
Hmmm, I'll take a look. Haven't tested it in months maybe theres something changed on gt

**Comment by DrOreo002** [comment]
Fixed.

**Comment by heysurfer** [comment]
@DrOreo002 Give Discord Contact Me HeySurfer#0654

**Comment by DrOreo002** [comment]
DrOreo002#3387
