### ISSUE TITLE
Doesn't Working Bot

### ISSUE THREAD

**Issue by sadMotion** [DrOreo002/GrowtopiaBot#5]
sooo i debug x86 the bot
and i do me owner
!follow is not follow
or !dance is dont do dance

**Comment by DrOreo002** [comment]
I'm gonna check that now

**Comment by DrOreo002** [comment]
Do you have this message printed on ur console when you join a world where your bot is?
`	if (actuallyOwner) cout << "Owner netID has been updated to " << objectData.netId << " username is " << ownerUsername;`

**Comment by sadMotion** [comment]
i cant get bro
help me on discord can ?
sadMotion#0872

**Comment by DrOreo002** [comment]
I can't give a free private lesson sorry
